### ISSUE TITLE
Error on UnityEngine.MaterialPropertyBlock.SetTexture

### ISSUE THREAD

**Issue by ysewnath** [Delacrowa/book-of-the-dead-environment-hdrp#1]
Hello! Thank you for providing this project, its been deprecated from the asset store so this is amazing that you have provided this resource!

However, there is one issue I've encountered that is preventing the project from loading:

ArgumentNullException: Value cannot be null.
Parameter name: value
UnityEngine.MaterialPropertyBlock.SetTexture (System.Int32 nameID, UnityEngine.Texture value) (at C:/buildslave/unity/build/Runtime/Export/Shader.cs:130)
UnityEngine.Rendering.PostProcessing.Dithering.Render (UnityEngine.Rendering.PostProcessing.PostProcessRenderContext context) (at Assets/_LocalPackages/botd.com.unity.postprocessing/PostProcessing/Runtime/Effects/Dithering.cs:31)
UnityEngine.Rendering.PostProcessing.PostProcessLayer.RenderBuiltins (UnityEngine.Rendering.PostProcessing.PostProcessRenderContext context, System.Boolean isFinalPass, System.Int32 releaseTargetAfterUse) (at Assets/_LocalPackages/botd.com.unity.postprocessing/PostProcessing/Runtime/PostProcessLayer.cs:883)
UnityEngine.Rendering.PostProcessing.PostProcessLayer.Render (UnityEngine.Rendering.PostProcessing.PostProcessRenderContext context) (at Assets/_LocalPackages/botd.com.unity.postprocessing/PostProcessing/Runtime/PostProcessLayer.cs:717)
UnityEngine.Experimental.Rendering.HDPipeline.HDRenderPipeline.RenderPostProcess (UnityEngine.Experimental.Rendering.HDPipeline.HDCamera hdcamera, UnityEngine.Rendering.CommandBuffer cmd, UnityEngine.Rendering.PostProcessing.PostProcessLayer layer) (at Assets/_LocalPackages/botd.com.unity.render-pipelines.high-definition/HDRP/RenderPipeline/HDRenderPipeline.cs:2024)
UnityEngine.Experimental.Rendering.HDPipeline.HDRenderPipeline.Render (UnityEngine.Experimental.Rendering.ScriptableRenderContext renderContext, UnityEngine.Camera[] cameras) (at Assets/_LocalPackages/botd.com.unity.render-pipelines.high-definition/HDRP/RenderPipeline/HDRenderPipeline.cs:1214)
UnityEngine.Experimental.Rendering.RenderPipelineManager.DoRenderLoop_Internal (UnityEngine.Experimental.Rendering.IRenderPipelineAsset pipe, UnityEngine.Camera[] cameras, System.IntPtr loopPtr) (at C:/buildslave/unity/build/Runtime/Export/RenderPipeline/RenderPipelineManager.cs:33)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at C:/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:179)

**Comment by Delacrowa** [comment]
Hi! Try downloading Unity 2018.4.20f1 and then:
1. Remove Library, Temp, obj and Logs folders in the project root folder
2. Open project via THIS version, agree if upgrate dialog appears
3. Close unity after opening process finished
4. Reopen and check it out. It's Ok if some assertations fail. Probably you should wait a bit for lags disappear.
