### ISSUE TITLE
Repository over it's LFS data quota

### ISSUE THREAD

**Issue by InVale** [Delacrowa/book-of-the-dead-environment-hdrp#2]
Hi!

With the asset deprecation on the asset store, finding your repository has been a light of hope for me. Sadly, attempting to pull the LFS files gives me the following error : "This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access."

Would it be possible to discuss with you another mean to get my hand on the project? Playing around with the Book of the Dead's assets seemed quite exciting. I guess otherwise I'll have to wait for the monthly bandwith reset in a few weeks...

**Comment by Delacrowa** [comment]
Hi! Check out the description - alternative link is already there :)

**Comment by InVale** [comment]
Thanks a lot. Got it up and running and the scene is absolutely gorgeous, I'm really thankful!
